#+title: Links
#+author: cashweaver
#+layout: post
#+description: A collection of links, updated monthly, to things I've read or otherwise thought were interesting or important, etc.
#+date: 2021-05-23
#+update_date: 2021-05-23
#+options: H:3 num:nil tags:nil toc:nil timestamps:t \n:nil ':nil
#+categories: blog
#+startup: showall
#+startup: hidestars

* Links
** 2021
*** May
**** [[http://www.aaronsw.com/weblog/theoryofchange][Theory of Change]] by Aaron Swartz :author_Aaron_Swartz:

#+begin_quote
A theory of change is the opposite of a theory of action — it works backwards from the goal, in concrete steps, to figure out what you can do to achieve it. To develop a theory of change, you need to start at the end and repeatedly ask yourself, "Concretely, how does one achieve that?"
#+end_quote

**** [[https://www.lesswrong.com/posts/BHYBdijDcAKQ6e45Z/cached-selves][Cached Selves]] by Anna Salamon :author_Anna_Salamon:

The idea that my actions are so easily influenced is disconcerting to say the least. The author is writing about commitment and consistency effects with the goal of reducing their effectiveness. I think it would be wise to attempt to incorporate a bit of the author's advice into how I conduct myself. The most straight-forward suggestion is to "[t]ake care never to say anything but what is best supported by the evidence, aloud or to yourself, lest you come to believe it". Identifying what is supported by the evidence and which evidence is trust-worthy is another can of worms.

**** [[https://www.lesswrong.com/posts/PBRWb2Em5SNeWYwwB/humans-are-not-automatically-strategic][Humans Are Not Automatically Strategic]] by Anna Salamon :author_Anna_Salamon:

#+begin_quote
We act from habit; we act from impulse or convenience when primed by the activities in front of us; we remember our goal and choose an action that feels associated with our goal.
#+end_quote

**** [[https://www.lesswrong.com/posts/puhPJimawPuNZ5wAR/learned-blankness][Learned Blankness]] by Anna Salamon :author_Anna_Salamon:

#+begin_quote
Martin Seligman coined the term "learned helplessness" to describe a condition in which someone has learned to behave as though they were helpless. I think we need a term for learned helplessness about thinking (in a particular domain). I’ll call this “learned blankness”. Folks who fall prey to learned blankness may still take actions -- sometimes my students practiced the procedures again and again, hired a tutor, etc. But they do so as though carrying out rituals to an unknown god -- parts of them may be trying, but their “understand X” center has given up.
#+end_quote

**** [[https://commoncog.com/blog/the-3-kinds-of-non-fiction-book/][The Three Kinds of Non-Fiction Books]] by Cedric Chin :author_Cedric_Chin:

I'm not sure if all non-fiction books could be adequately categorized by these three labels. Nonetheless, I'm grateful for the vocabulary to describe books I've read that seem like over-stuffed musings on a single idea which would have been better served by a short blog post rather than a book.

**** [[https://commoncog.com/blog/what-is-a-career-moat/][What is a Career Moat?]] by Cedric Chin :author_Cedric_Chin:

#+begin_quote
A career moat is an individual's ability to maintain competitive advantages over your competition (say, in the job market) in order to protect your long term prospects, your employability, and your ability to generate sufficient financial returns to support the life you want to live.
#+end_quote

**** [[https://www.lesswrong.com/posts/4iLk2rxTguFqHHs3Y/the-power-of-pomodoros][The Power of Pomodoros]] by elharo :author_elharo:

#+begin_quote
Pomodoros aren’t (for me) a means of avoiding procrastination or dividing time among projects. They’re a way of blasting through Ugh fields.
#+end_quote

**** [[https://www.lesswrong.com/posts/TyswYDeub7mxMXCgi/the-monthly-newsletter-as-thinking-tool][The Monthly Newsletter as a Thinking Tool]] by Matt Freeman :author_Matt_Freeman:

This post.

**** [[https://www.flightfromperfection.com/(a).html][(a)]] by Milan Griffes :author_Milan_Griffes:

I like the idea of including an archive link when linking to off-domain content. It seems like something that could be automated through some "presubmit" step of the publishing process. I've looked around but haven't found an addon/extension for any of the popular blogging solutions which provides an easy way to include such links. I expect that I won't bother to include them so long as I would have to include them manually. The URL to the off-domain content will be present and determined readers will be able to consult archive.org/etc on their own to achieve the same result.

I also notice that the author [[https://www.flightfromperfection.com/the-best-explanation-of-modern-monetary-theory.html][includes (sometimes long) relevant quotes from links they cite]], or even a [[https://www.flightfromperfection.com/specific-benefits-of-meditation.html][long quote and nothing else]]. I think this is a fantastic practice which accomplishes most of the goal of "(a)".

**** [[https://www.neelnanda.io/blog/29-meaningful-rest][Meaningful Rest]] by Neel Nanda :author_Neel_Nanda:

#+begin_quote
An exercise: Set a 5 minute timer, and list the things you want to do when you feel tired and low-energy. Then, set another 5 minute timer, and list the things you feel rejuvenated after having done - the things you like doing when low-energy.

If you’re anything like me, these lists are basically disjoint!
#+end_quote

#+begin_quote
Most situations in my life have a default response, and that takes no effort to follow. To deviate from the default response, I need to spend a scarce resource - willpower. Being tired is essentially being low on willpower, and the problem is that my default actions when low willpower do not regenerate willpower. (I elaborate far more on this model in [[https://www.neelnanda.io/blog/mini-blog-post-19-on-systems-living-a-life-of-zero-willpower][this post]])
#+end_quote
**** [[https://blog.samaltman.com/productivity][Productivity]] by Sam Altman :author_Sam_Altman:

There is a lot of good advice in here. I especially appreciated the point about avoiding productivity porn. "Chasing productivity for its own sake isn't helpful". I've done that chase before and at best it's a time sink and at worst it's a form of self-deception. As such, I want to be sure to do more than just read the article and then proceed with my life as it was before. I've had more success integrating change gradually and building on small accomplishments as opposed to attempting to overhaul all of my habits at once. I'll try to tackle one piece of advice weekly, of my own highlights from the article, and attempt to work it into my life that week.

**** [[https://www.lesswrong.com/posts/KwdcMts8P8hacqwrX/noticing-the-taste-of-lotus][Noticing the Taste of Lotus]] by Valentine :author_Valentine:

The idea of noticing the taste of lotus is closely related to mindfulness and attention. The importance of, and ways to maintain, focus and attention are a common theme in several other articles recently (at least recent to me and my discovery of them).

The author's follow-up review of their own writing distinguishes a few claims made in the piece:

#+begin_quote
1. External forces can shape what we want to do. (I.e., there are lotuses.)

2. It's possible to notice this in real time. (I.e., you can notice the taste of lotuses.)

3. It's good to do so. Otherwise we find our wanting aligned with others' goals regardless of how they relate to our own.

4. If you notice this, you'll find yourself wanting to spit out lotuses that you can tell pull you away from your goals.
#+end_quote

I like this way of breaking a piece of writing apart into claims. Doing so reminds me of breaking a commit down into small, independent, chunks and all the benefits that come with that practice. There's a balancing act between leveraging links to other, single-purpose, writing throughout a piece and writing a monolithic entry which can be taken as is without further context or external references.

As for the claims themselves, I identify with the way the author has phrased claim #3. I find myself at the precipice of rabbit holes regularly with regard to video games. [[https://www.factorio.com/][Factorio]], for example, is a game that I enjoyed playing so much that I had to cut myself off from it. I would find myself thinking about my factory, and future factories, throughout the day. The optimization problems were enchanting and satisfied a need to accomplish and be productive so well that I dropped a lot of other goals/etc and replaced them, for a time, with Factorio. It's not that Factorio is bad -- it's a fantastic game -- but that I discover, after coming out of the haze of hours and hours of perfecting resource gathering, delivery, and processing, that I've realigned my goals around the game and that those new goals won't take me where I want to go.

**** [[https://zwbetz.com/attention-is-my-most-valuable-asset-for-productivity-as-a-software-developer/][Attention Is My Most Valuable Asset for Productivity as a Software Developer]] by Zachary Betz :author_Zachary_Betz:

I think the author makes a good point. Perhaps I'm less interested than others would be as I've seen these ideas already expressed by Cal Newport.

**** [[https://www.lesswrong.com/posts/DoLQN5ryZ9XkZjq5h/tsuyoku-naritai-i-want-to-become-stronger][Tsuyoku Naritai! (I Want To Become Stronger)]] by Eliezer Yudkowsky :author_Elizer_Yudkowsky:

#+begin_quote
Tsuyoku naritai is Japanese. Tsuyoku is “strong”; naru is “becoming,” and the form naritai is “want to become.” Together it means, “I want to become stronger,” and it expresses a sentiment embodied more intensely in Japanese works than in any Western literature I’ve read. You might say it when expressing your determination to become a professional Go player—or after you lose an important match, but you haven’t given up—or after you win an important match, but you’re not a ninth-dan player yet—or after you’ve become the greatest Go player of all time, but you still think you can do better. That is tsuyoku naritai, the will to transcendence
#+end_quote

**** [[https://www.lesswrong.com/posts/SGR4GxFK7KmW7ckCB/something-to-protect][Something to Protect]] by Eliezer Yudkowsky :author_Elizer_Yudkowsky:

#+begin_quote
The Art must have a purpose other than itself, or it collapses into infinite recursion.
#+end_quote

**** [[https://guzey.com/personal/why-have-a-blog/][Why You Should Start a Blog Right Now]] by Alexy Guzey :author_Alexy_Guzey:

#+begin_quote
This fact is very frequently lost when discussing writing: writing not only helps you to understand what’s going on and to crystallize your thoughts, it actually makes you think of new ideas and come up with solutions to your problems.
#+end_quote

**** [[https://www.lesswrong.com/posts/zMxrkFrB6ka4Lb7fM/making-yourself-small][Making Yourself Small]] by Helen :author_Helen:

#+begin_quote
.. probably the most important thing is your mental/emotional state - a friend suggested “not wanting to startle a small bird” as an mindset to inhabit, to encourage yourself to become “smaller”.
#+end_quote

**** [[https://www.lesswrong.com/posts/5okDRahtDewnWfFmz/seeing-the-smoke][Seeing the Smoke]] by Jacob Falkovich :author_Jacob_Falkovich:

#+begin_quote
As Eliezer reminded us, most people sitting alone in a room will quickly get out if it starts filling up with smoke. But if two other people in the room seem unperturbed, almost everyone will stay put. That is the result of a famous experiment from the 1960s and its replications — people will sit and nervously look around at their peers for 20 minutes even as thick smoke starts obscuring their vision.
#+end_quote

#+begin_quote
In a lake, there is a patch of lily pads. Every day, the patch doubles in size. If it takes 48 days for the patch to cover the entire lake, how long would it take for the patch to cover half of the lake?

Exponential growth is hard for people to grasp.  Most people answer ’24’ to the above question, or something random like ’35’. It’s counter-intuitive to people that the lily pads could be barely noticeable on day 44 and yet completely cover the lake on day 48.
#+end_quote

**** [[https://www.benkuhn.net/impatient/][Be Impatient]] by Ben Kuhn :author_Ben_Kuhn:

#+begin_quote
Being impatient is the best way to get faster at things. And across a surprising number of domains, being really fast correlates strongly with being effective.
#+end_quote

**** [[https://www.benkuhn.net/attention][Attention is your scarcest resource]] by Ben Kuhn :author_Ben_Kuhn:

#+begin_quote
"The output of knowledge workers is extremely skewed based on focus. The productivity tiers seem to be:

<10% focused on the job at hand: meaningful risk of getting fired.

10-50% focus: “meets expectations,” gets regular raises.

50%+ focus: superstar, 10x engineer, destined for greatness."

/[[https://diff.substack.com/p/the-future-of-remote-work-is-not][Byrne Hobart]]/

"50%+ focus" is roughly when something becomes the top idea in your mind. It’s when you start caring enough to think about it in the shower. It’s when you start habitually asking "how could this go faster?" It’s when you get relentlessly resourceful. It’s around when you start annoying your coworkers and/or significant other, although that part is avoidable with practice.

Most importantly, you can only be 50%+-focused on one thing at a time—or zero, in bad cases. That makes it critical to conserve your attention, so that you can spend it on what matters.
#+end_quote
